name: docker
on:
    push:
      branches:
        - main

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Run make docker-build
      run: make docker-build
    - name: Run make docker-tag
      run: make docker-tag
    - name: Run make docker-push
      run: make docker-push
